//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIWeather.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://192.168.1.100:554/stream")]
        public string RtspUrl {
            get {
                return ((string)(this["RtspUrl"]));
            }
            set {
                this["RtspUrl"] = value;
            }
        }        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RtspUsername {
            get {
                return ((string)(this["RtspUsername"]));
            }
            set {
                this["RtspUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RtspPassword {
            get {
                return ((string)(this["RtspPassword"]));
            }
            set {
                this["RtspPassword"] = value;
            }
        }        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CheckIntervalMinutes {
            get {
                return ((int)(this["CheckIntervalMinutes"]));
            }
            set {
                this["CheckIntervalMinutes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSunAltitudeLimit {
            get {
                return ((bool)(this["UseSunAltitudeLimit"]));
            }
            set {
                this["UseSunAltitudeLimit"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6.0")]
        public double SunAltitudeLimitDegrees {
            get {
                return ((double)(this["SunAltitudeLimitDegrees"]));
            }
            set {
                this["SunAltitudeLimitDegrees"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70.0")]
        public double CloudCoverageThreshold {
            get {
                return ((double)(this["CloudCoverageThreshold"]));
            }
            set {
                this["CloudCoverageThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60.0")]
        public double CloudCoverageSafeThreshold {
            get {
                return ((double)(this["CloudCoverageSafeThreshold"]));
            }
            set {
                this["CloudCoverageSafeThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseGitHubModels {
            get {
                return ((bool)(this["UseGitHubModels"]));
            }
            set {
                this["UseGitHubModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GitHubToken {
            get {
                return ((string)(this["GitHubToken"]));
            }
            set {
                this["GitHubToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gpt-4o")]
        public string SelectedModel {
            get {
                return ((string)(this["SelectedModel"]));
            }
            set {
                this["SelectedModel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Local")]
        public string AnalysisProvider {
            get {
                return ((string)(this["AnalysisProvider"]));
            }
            set {
                this["AnalysisProvider"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenAIKey {
            get {
                return ((string)(this["OpenAIKey"]));
            }
            set {
                this["OpenAIKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GeminiKey {
            get {
                return ((string)(this["GeminiKey"]));
            }
            set {
                this["GeminiKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GeminiRequestEveryChecks {
            get {
                return ((int)(this["GeminiRequestEveryChecks"]));
            }
            set {
                this["GeminiRequestEveryChecks"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnthropicKey {
            get {
                return ((string)(this["AnthropicKey"]));
            }
            set {
                this["AnthropicKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:11434/v1")]
        public string OllamaBaseUrl {
            get {
                return ((string)(this["OllamaBaseUrl"]));
            }
            set {
                this["OllamaBaseUrl"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OllamaDisableThinking {
            get {
                return ((bool)(this["OllamaDisableThinking"]));
            }
            set {
                this["OllamaDisableThinking"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxDataAgeMinutes {
            get {
                return ((int)(this["MaxDataAgeMinutes"]));
            }
            set {
                this["MaxDataAgeMinutes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteNotes {
            get {
                return ((string)(this["SiteNotes"]));
            }
            set {
                this["SiteNotes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CaptureMode {
            get {
                return ((int)(this["CaptureMode"]));
            }
            set {
                this["CaptureMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string INDIDeviceName {
            get {
                return ((string)(this["INDIDeviceName"]));
            }
            set {
                this["INDIDeviceName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FolderPath {
            get {
                return ((string)(this["FolderPath"]));
            }
            set {
                this["FolderPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAscomSafetyMonitor {
            get {
                return ((bool)(this["UseAscomSafetyMonitor"]));
            }
            set {
                this["UseAscomSafetyMonitor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AscomSafetyMonitorProgId {
            get {
                return ((string)(this["AscomSafetyMonitorProgId"]));
            }
            set {
                this["AscomSafetyMonitorProgId"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WriteSafetyStatusFile {
            get {
                return ((bool)(this["WriteSafetyStatusFile"]));
            }
            set {
                this["WriteSafetyStatusFile"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\miche\\Documents\\N.I.N.A\\sky_conditions.txt")]
        public string SafetyStatusFilePath {
            get {
                return ((string)(this["SafetyStatusFilePath"]));
            }
            set {
                this["SafetyStatusFilePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DatasetEnabled {
            get { return ((bool)(this["DatasetEnabled"])); }
            set { this["DatasetEnabled"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DatasetPaused {
            get { return ((bool)(this["DatasetPaused"])); }
            set { this["DatasetPaused"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatasetDirectory {
            get { return ((string)(this["DatasetDirectory"])); }
            set { this["DatasetDirectory"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DatasetSamplingIntervalMinutes {
            get { return ((int)(this["DatasetSamplingIntervalMinutes"])); }
            set { this["DatasetSamplingIntervalMinutes"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DatasetSampleEveryChecks {
            get { return ((int)(this["DatasetSampleEveryChecks"])); }
            set { this["DatasetSampleEveryChecks"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double DatasetMaxSizeGb {
            get { return ((double)(this["DatasetMaxSizeGb"])); }
            set { this["DatasetMaxSizeGb"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double DatasetMinFreeSpaceGb {
            get { return ((double)(this["DatasetMinFreeSpaceGb"])); }
            set { this["DatasetMinFreeSpaceGb"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public int DatasetImageWidth {
            get { return ((int)(this["DatasetImageWidth"])); }
            set { this["DatasetImageWidth"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int DatasetImageHeight {
            get { return ((int)(this["DatasetImageHeight"])); }
            set { this["DatasetImageHeight"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double DatasetImageScalePercent {
            get { return ((double)(this["DatasetImageScalePercent"])); }
            set { this["DatasetImageScalePercent"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85")]
        public int DatasetJpegQuality {
            get { return ((int)(this["DatasetJpegQuality"])); }
            set { this["DatasetJpegQuality"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double DatasetDisagreementThreshold {
            get { return ((double)(this["DatasetDisagreementThreshold"])); }
            set { this["DatasetDisagreementThreshold"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DatasetNearDuplicateHammingDistance {
            get { return ((int)(this["DatasetNearDuplicateHammingDistance"])); }
            set { this["DatasetNearDuplicateHammingDistance"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DatasetSaveTeacherRaw {
            get { return ((bool)(this["DatasetSaveTeacherRaw"])); }
            set { this["DatasetSaveTeacherRaw"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DatasetRecordQuarantine {
            get { return ((bool)(this["DatasetRecordQuarantine"])); }
            set { this["DatasetRecordQuarantine"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standalone")]
        public string ClusterNodeMode {
            get { return ((string)(this["ClusterNodeMode"])); }
            set { this["ClusterNodeMode"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18910")]
        public int ClusterListenPort {
            get { return ((int)(this["ClusterListenPort"])); }
            set { this["ClusterListenPort"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.10.121:18910")]
        public string ClusterPrimaryUrl {
            get { return ((string)(this["ClusterPrimaryUrl"])); }
            set { this["ClusterPrimaryUrl"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClusterSharedToken {
            get { return ((string)(this["ClusterSharedToken"])); }
            set { this["ClusterSharedToken"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ClusterPollSeconds {
            get { return ((int)(this["ClusterPollSeconds"])); }
            set { this["ClusterPollSeconds"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ClusterStaleSeconds {
            get { return ((int)(this["ClusterStaleSeconds"])); }
            set { this["ClusterStaleSeconds"] = value; }
        }
    }
}
